
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>ChargeBow</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="WispF.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Localization\" />
  </ItemGroup>
</Project>